### ISSUE TITLE
check details after removing next sib

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelnut-popl17#11]
- [x] line numbers in example
- [x] rule statements
- [x] no text that's out of date and talks about next sib
- [x] include in discussion of action macros?

**Comment by ivoysey** [comment]
i believe that i did these things correctly, but it'd be good if someone else double checked me. the relevant commit to look at the diff for is https://github.com/hazelgrove/hazelnut-popl17/commit/95b35587ef8cae23d2625f4c843db066664679c5

**Comment by cyrus-** [comment]
Just took a look, looks right to me.

**Comment by ivoysey** [comment]
Alright. Leave this issue open until we figure out if we want to make a comment in the text about derived actions? `next sib` but also `{left, right}-most hole` and `only hole remaining` are sort of the obvious examples to motivate that, now.
