### ISSUE TITLE
turn inj_1/inj_2 into inj_L/inj_R?

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazelnut-popl17#16]
this is what the implementation does, because I can't make datatype constructors labeled 1 and 2. should keep things consistent across the impl/paper/agda

**Comment by ivoysey** [comment]
what's the inconsistency? i don't quite understand. in the agda, i believe the injections for sums are labeled with `l` and `r` rather than numbers, which is the notation i'm familiar with for binary rather than n-ary sums.

**Comment by cyrus-** [comment]
in the paper it says "i \in {1, 2}" rather than "i \in {L, R}". should be an easy fix

**Comment by ivoysey** [comment]
Ah, ok. I'm in favor of l and r. Beyond what I said above, in the agda i use 1 and 2 to denote rules that fire in similar situations but do different things, so things like

```
 SAConPlus1 : {Γ : ·ctx} {e : ė} {t : τ̇} →
                (t ~ num) →
                Γ ⊢ ▹ e ◃ => t ~ construct plus ~> e ·+₂ ▹ <||> ◃  => num
      SAConPlus2 : {Γ : ·ctx} {e : ė} {t : τ̇} →
                (t ~̸ num) →
                Γ ⊢ ▹ e ◃ => t ~ construct plus ~> <| e |> ·+₂ ▹ <||> ◃  => num
```

so using that to number injections would be a little confusing.

**Comment by cyrus-** [comment]
@matthewhammer can you do this one
