### ISSUE TITLE
explain rules column after zipper rules

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazelnut-popl17#2]
point out that the rules column in the examples give the relevant _non-zipper_ rule

**Comment by cyrus-** [comment]
maybe also mention that the full derivation is listed in the agda supplemental material

**Comment by ivoysey** [comment]
c.f. https://github.com/hazelgrove/agda-popl17/commit/d1b6c34c4ae9afa58f00c951ea64fa4c3597cab5
