### ISSUE TITLE
cite "synthesizer generator" 

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelnut-popl17#28]
i think it's in the bibliography, might want to double check that we have the right text about it in the paper itself. bob felt that this is foundational work relating to our editorializer, so we should be clear about that.

**Comment by ivoysey** [comment]
check for other work from cornell around the same time? greg johnson was the name of the PI that did a bunch of structure editing stuff at that time and place.

**Comment by cyrus-** [comment]
we cite both the program synthesizer and the synthesizer generator.
