### ISSUE TITLE
rwh citations from ian's pop seminar

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelnut-popl17#33]
bob mentioned a bunch of things we should look into during Q&A in my talk; cyrus has a list somewhere.

**Comment by cyrus-** [comment]
bob mentioned:
- look into lcf/nuprl/etc refinement logics
- bob mentioned he had coauthored a paper with chlipala and some others on bidirectional typing. I don't think it's the "strict bidirectional typing" one. see if we can find that.
- guarantee tactics by Constable and Smith
- "that's how I type contexts in my book" -- we should mention something about how contextual dynamics use a similar definition.

@ivoysey can you investigate these things and report back?

**Comment by ivoysey** [comment]
wrt chilpala, the only thing on both of their websites of publications that
has them both as authors is the strict bidirectional type checking paper,
which we already cite.

---Ian

**Comment by cyrus-** [comment]
seems we didn't find anything of note here.
