### ISSUE TITLE
refactor rules

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelnut-popl17#7]
pull the rules out into a separate file so it's harder to get inconsistencies between the paper text and the appendix. this should be done so that the numbering is the same in both places in the produced pdf, so probably just make commands per rule or something.

**Comment by ivoysey** [comment]
I've started doing this. It's more delicate than I really expected. The TeX in each place isn't quite the same, so you have to be careful to abstract the right thing. I think I'm as likely to introduce inconsistencies by doing this as by needing to copy the TeX over into each place.

With that, and given that these rules aren't likely to change before submission, I propose that: we don't refactor this TeX; but instead take a solemn vow to be more principled in the future, and maybe consider using Ott.

**Comment by cyrus-** [comment]
Yeah that sounds fine.

**Comment by cyrus-** [comment]
One thing I figured out how to do recently is have the equation numbers for
one copy of a rule link to the corresponding equation number in another. So
if we ultimately have an appendix like the one we have now at least the
numbers won't be duplicated.
